language: node_js
node_js:
  - "node"
script: echo "Running tests against $(node -v)..."
env:
  - ARTIFACTS_KEY=AKIAXX6WT6EGFIRLLZ7F ARTIFACTS_BUCKET=harrythaotesting ARTIFACTS_PATHS="./test-report.html"
  - CAN_FAIL=false
jobs:
  allow_failures: 
    env:
      - CAN_FAIL=true
  include:
    - stage: Linting
      script: npm run lint
    - stage: Testing & producing coverage
      env:
       - CAN_FAIL=true
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | coveralls
    - stage: Generating coverage
      script: coveralls < coverage/lcov.info
addons:
  artifacts:
    debug: true
    paths:
      - ./test-report.html
    target_paths: $TRAVIS_BUILD_NUMBER
    working_dir: WORKING_DIR
    s3_region: us-east-1