language: node_js
node_js:
  - "node"
script: echo "Running tests against $(node -v)..."
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - stage: Generating coverage
      script: COVERALLS_FLAG_NAME=test-1 make test-coveralls-1
    - stage: Linting
      script: npm run lint
    - stage: Testing & producing coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
notifications:
  webhooks: https://coveralls.io/webhook
addons:
  artifacts: true
  paths:
    - $(git ls-files -o | tr "\n" ":")
    - $(ls /var/log/*.log | tr "\n" ":")