language: node_js
node_js:
  - "node"
script: echo "Running tests against $(node -v)..."
jobs:
  include:
    - stage: Generating coverage
      script: coveralls < coverage/lcov.info
    - stage: Linting
      script: npm run lint
    - stage: Testing & producing coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | coveralls
addons:
  artifacts: true
  paths:
    - $(git ls-files -o | tr "\n" ":")
    - $(ls /var/log/*.log | tr "\n" ":")